### ISSUE TITLE
Some output filenames have changed in the sepia toolbox

### ISSUE THREAD

**Issue by lukeje** [fil-physics/MPM_QSM#3]
A recent release of the sepia toolbox has changed the name of some of its output files, specifically, `sepia_QSM.nii.gz` has become `sepia_Chimap.nii.gz`, and `sepia_local-field.nii.gz` has become `sepia_localfield.nii.gz`. As the old filenames are referenced explicitly in the current code, this causes a crash if the latest version of the sepia toolbox is used.

I have implemented the necessary changes in a [fork](https://github.com/lukeje/MPM_QSM), but note that that will break backwards compatibility with older versions of the sepia toolbox.

**Comment by baskadym** [comment]
Dear Luke,
Thanks a lot for raising this issue!
I've prepared a pull request to this repo:
https://github.com/fil-physics/MPM_QSM/pull/4

with the changes, you have suggested plus back compatibility.
Would you like to try it out and let me know if that works for you?

**Comment by lukeje** [comment]
@baskadym Thank you; your suggested changes worked for me.
